# This code is generated by PyUIbuilder: https://github.com/PaulleDemon/PyUIBuilder

import tkinter as tk

main = tk.Tk()
main.config(bg="#E4E2E2")
main.title("Main Window")

text = tk.Text(master=main)
text.config(bg="#fff", fg="#000")
text.pack(side=tk.LEFT, padx=10, pady=10, anchor='nw')

option_menu_options = ["option 1"]
option_menu_var = tk.StringVar(value="Select option")
option_menu = tk.OptionMenu(main, option_menu_var, *option_menu_options)
option_menu.config(bg="#fff", fg="#000")
option_menu.pack(side=tk.LEFT, padx=10, pady=10, anchor='nw')

spin_box = tk.Spinbox(master=main)
spin_box.config(from_=0, to=100, increment=1, value=0, bg="#fff", fg="#000")
spin_box.pack(side=tk.LEFT, padx=10, pady=10, anchor='nw')


main.mainloop()